"""ACAR V5 Stage-1B pinned DSP preprocessing config (pure/stdlib). The config is FIXED in code (not generated by the trainer) and
canonicalized → preprocessing_config_sha256. The real mne DSP (Stage-1B run) must produce windows conforming to this exactly.
"""
from __future__ import annotations
import hashlib
import json

# exact 19-channel 10-20 order (the substrate montage)
CHANNELS_19 = ("Fp1", "Fp2", "F7", "F3", "Fz", "F4", "F8", "T3", "C3", "Cz", "C4", "T4", "T5", "P3", "Pz", "P4", "T6", "O1", "O2")

PREPROCESSING_CONFIG = {
    "schema": "acar_v5_preprocessing_v1",
    "channels": list(CHANNELS_19),          # exact set AND order
    "n_channels": 19,
    "resample_hz": 128,
    "bandpass_hz": [0.5, 45.0],
    "window_sec": 4.0,
    "window_samples": 512,                  # 4 s × 128 Hz
    "window_overlap": 0.0,                   # non-overlapping (pinned)
    "reference": "average",                  # pinned re-reference policy
    "notch_hz": None,                        # explicitly none
    "units": "microvolt",
    "trial_normalization": "per_trial_zscore",
    "bad_channel_policy": "fail_closed",     # missing / duplicate canonical channel → fail
    # the 19 canonical channels must all be PRESENT (missing → fail) and are picked + reordered to the canonical order;
    # extra non-canonical channels are dropped; a duplicated canonical channel fails closed. Code (real_mne_reader) matches this.
    "required_channels": "all_19_canonical_present",
    "extra_channel_policy": "drop_non_canonical_after_required_19_present",
    "duplicate_channel_policy": "fail_closed",
    "channel_output_order": "canonical_pinned",
    # Stage-1B10: the OUTPUT montage stays the old-10-20 canonical order above; a PINNED input-channel alias layer maps common
    # modern 10-10 temporal names to the same historical electrodes BEFORE the canonical pick (input names are stripped +
    # case-normalized, so Fp1/FP1/fp1 collapse). Extra channels are still dropped; two raw channels mapping to the same logical
    # channel FAIL. This makes old-name and modern-name cohorts semantically symmetric without changing the trained layout.
    "logical_montage_policy": "old_10_20_canonical_with_reviewed_10_10_aliases",
    "channel_alias_schema_version": "acar_v5_channel_alias_v1",
    "input_channel_aliases": {"T7": "T3", "T8": "T4", "P7": "T5", "P8": "T6"},
    "duplicate_logical_channel_policy": "fail_closed",
}


def canonical_json():
    return json.dumps(PREPROCESSING_CONFIG, sort_keys=True, separators=(",", ":"))


def config_sha256():
    return hashlib.sha256(canonical_json().encode()).hexdigest()
