"""ACAR V5 Stage-1B pinned EEGNet + source-state training spec (pure/stdlib). Fixed in code (not generated by the trainer) and
canonicalized → a hash the run records. The real trainer (Stage-1B run) must train under exactly this spec, on FIT (train/val)
subjects only, deterministically.
"""
from __future__ import annotations
import hashlib
import json
from acar.v5 import protocol as P

TRAINING_CONFIG = {
    "schema": "acar_v5_training_v1",
    "architecture": "EEGNet",
    "n_chans": 19,
    "n_times": 512,
    "n_classes": 2,                          # binary disease vs control
    "label_mapping": {"control": 0, "case": 1},
    "optimizer": "adam",
    "lr": 1e-3,
    "weight_decay": 0.0,
    "batch_size": 64,
    "max_epochs": 100,
    "early_stopping_metric": "val_loss",
    "early_stopping_patience": 15,
    "checkpoint_selection": "best_val_loss",
    "deterministic": True,
    "torch_threads": 1,
    "seed_field": "substrate_seed",          # the fold ref's seed drives all RNG
    "source_state": "class_conditional_gaussian_tangent",   # what the source-state artifact contains
    "trains_on": "FIT_train_val_only",       # NEVER CAL/EVAL
    "reads_labels": "FIT_training_only",     # labels only via the FIT training view
}
assert TRAINING_CONFIG["n_chans"] == 19 and TRAINING_CONFIG["n_times"] == 512
assert TRAINING_CONFIG["n_classes"] == len(P.FEATURES) - len(P.FEATURES) + 2   # ==2 (guard the literal)


def canonical_json():
    return json.dumps(TRAINING_CONFIG, sort_keys=True, separators=(",", ":"))


def config_sha256():
    return hashlib.sha256(canonical_json().encode()).hexdigest()
