"""C86H F1/F2 real-implementation tests — 11-channel model + interface epoching + the
ds007221 BIDS adapter + MOABB adapter, validated against SYNTHETIC fixtures / mocks. No real
EEG/label is touched.
"""
import os

import numpy as np
import pytest

torch = pytest.importorskip("torch")
mne = pytest.importorskip("mne")
pytest.importorskip("mne_bids")

from oaci.active_testing.c86h import f1f2_field as F
from oaci.active_testing.c86h import contract as K


def test_11_channel_model_forward():
    m = F.build_c86h_model()
    assert F.IN_CHANS == 11 and F.IN_TIMES == 480
    out = m(torch.randn(4, F.IN_CHANS, F.IN_TIMES))
    logits = out.logits if hasattr(out, "logits") else out
    assert tuple(logits.shape) == (4, 2)


def _synthetic_epochs(sfreq=200.0, n=20, extra=("EXTRA1",)):
    ch = list(K.INTERFACE_CHANNELS) + list(extra)
    rng = np.random.default_rng(0)
    data = rng.standard_normal((n, len(ch), int(sfreq * 4))) * 1e-6
    info = mne.create_info(ch, sfreq, ch_types="eeg")
    ev = np.column_stack([np.arange(n), np.zeros(n, int),
                          np.array([1 if k % 2 else 2 for k in range(n)])])
    return mne.EpochsArray(data, info, events=ev,
                           event_id={"right_hand": 1, "left_hand": 2}, tmin=0.0, verbose="error")


def test_interface_epoching_maps_to_11ch_160hz():
    ep = _synthetic_epochs()
    X, y = F.interface_epochs(ep)
    assert X.shape[1] == 11 and X.shape[2] == 480
    assert set(y.tolist()) <= {0, 1}
    assert np.all(np.isfinite(X))


def test_interface_epoching_c86e_on_missing_channel():
    ep = _synthetic_epochs()
    ep = ep.drop_channels(["FC5"])                       # remove a required interface channel
    with pytest.raises(F.C86EError):
        F.interface_epochs(ep)


def test_ds007221_bids_adapter_roundtrip_and_deterministic(tmp_path):
    root = str(tmp_path / "bids")
    F.write_synthetic_ds007221_fixture(root, [37, 40], n_trials=24, seed=1)
    X, y, tids, sha = F.load_ds007221_bids(root, "sub-37")
    assert X.shape[1] == 11 and X.shape[2] == 480
    assert set(y.tolist()) <= {0, 1}
    assert len(tids) == len(y) == X.shape[0]
    assert len(set(tids)) == len(tids)                   # unique stable trial ids
    # deterministic replay: reload gives identical trial ids + provenance sha
    X2, y2, tids2, sha2 = F.load_ds007221_bids(root, "sub-37")
    assert tids == tids2 and sha == sha2
    assert np.array_equal(y, y2)


def test_ds007221_bids_adapter_c86e_subject_out_of_range(tmp_path):
    root = str(tmp_path / "bids")
    F.write_synthetic_ds007221_fixture(root, [37], n_trials=12, seed=2)
    with pytest.raises(F.C86EError):
        F.load_ds007221_bids(root, "sub-10")             # not in locked 37..73


def test_ds007221_bids_adapter_c86e_when_absent(tmp_path):
    root = str(tmp_path / "empty"); import os; os.makedirs(root, exist_ok=True)
    with pytest.raises(F.C86EError):
        F.load_ds007221_bids(root, "sub-37")             # no hybrid acquisition present


def test_moabb_adapter_with_mock_loader():
    def mock(name, subs):
        return {s: (np.random.randn(20, F.IN_CHANS, F.IN_TIMES),
                    ["left_hand", "right_hand"] * 10) for s in subs}
    r = F.load_moabb_dataset("Lee2019_MI", [1, 2], loader=mock)
    assert set(r) == {1, 2}
    X, y = r[1]
    assert X.shape == (20, 11, 480) and set(y.tolist()) <= {0, 1}


def test_real_field_manifest_content_addressed_replay(tmp_path):
    """The validator OPENS + re-hashes every field NPZ + weight file and fails closed on any
    cardinality corruption or byte-level tamper (real files generated by F2)."""
    import glob
    import json
    import types
    from oaci.active_testing.c86h import f1f2, f1f2_train
    from oaci.active_testing.c86h.f1f2_field import build_c86h_model

    def mock_cell(X, y, d, seed, preset):
        def rec(o):
            return types.SimpleNamespace(model_state=build_c86h_model().state_dict(),
                                         model_hash="", epoch=o)
        return [("ERM", rec(0), 0), ("OACI", rec(1), 1)]      # 2 candidates/context

    def src(panel, seed, level):
        return f1f2_train.build_synthetic_source(2, 4, seed=abs(hash((panel, seed, level))) % 1000)

    zoo_root = str(tmp_path / "zoo")
    zoo = f1f2_train.f1_train_zoo(src, zoo_root, preset=f1f2_train.TINY, cell_trainer=mock_cell)

    def tgt():
        rng = np.random.default_rng(0); n = 88
        y = np.array([0, 1] * (n // 2))
        X = rng.standard_normal((n, 11, 480)) + y[:, None, None] * 0.5
        yield "SYN", 1, X, y, [f"1_t{i}" for i in range(n)], "raw"

    field_root = str(tmp_path / "field")
    f1f2_train.f2_generate_predictions(zoo, zoo_root, tgt, field_root)
    contract = {"target_cohort": {("SYN", 1): "SYN"}, "cohort_dataset": {"SYN": "SYN"},
                "n_targets": 1, "n_candidates_per_context": 2, "n_models": 8 * 2, "n_contexts": 8}
    assert f1f2.validate_real_field_manifest(
        field_root, contract=contract, zoo_root=zoo_root)["n_targets"] == 1
    mpath = os.path.join(field_root, f1f2.REAL_FIELD_MANIFEST_NAME)
    # cardinality corruption -> C86-E
    man = json.load(open(mpath)); man["construction_evaluation_overlap"] = 1
    json.dump(man, open(mpath, "w"))
    with pytest.raises(f1f2.C86EError):
        f1f2.validate_real_field_manifest(field_root, contract=contract, zoo_root=zoo_root)
    # byte-level tamper of a field NPZ -> content-addressed replay fails
    man["construction_evaluation_overlap"] = 0; json.dump(man, open(mpath, "w"))
    ff = glob.glob(os.path.join(field_root, "acquisition_unlabeled_pool", "*.npz"))[0]
    with open(ff, "ab") as fh:
        fh.write(b"corrupt")
    with pytest.raises(f1f2.C86EError):
        f1f2.validate_real_field_manifest(field_root, contract=contract, zoo_root=zoo_root)
