#!/usr/bin/env python
"""CIGL Phase 4A — collect compact evidence tables for paper framing (NO training, NO GPU).

Reads the tracked confirmation summary JSON (if present under results/cigl/) and emits compact CSV/Markdown
tables for the manuscript. Pure standard library only — no deep-learning or training-module imports, and
no accelerator use. If a summary JSON is missing it FAILS GRACEFULLY (warns, still emits the static
claims-scope table). Generated tables are gitignored unless explicitly approved.

    python scripts/collect_cigl_evidence_tables.py --dry_run --out_dir /tmp/cigl_tables_check
    python scripts/collect_cigl_evidence_tables.py --out_dir results/cigl/paper_tables
"""
from __future__ import annotations
import argparse
import csv
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
RESULTS = REPO / "results" / "cigl"

# (label, summary JSON path, summary-meta dataset note) for the two fixed-candidate confirmations.
CONFIRMATIONS = [
    ("bnci2014_confirm", RESULTS / "phase3a_dgcnn_gn_multifold_confirmation"
     / "BNCI2014_001_dgcnn_gn_multifold_summary.json", "BNCI2014_001 (4-class, chance 0.25); fold-0=dev, primary folds 1-8"),
    ("bnci2015_confirm", RESULTS / "phase3a_dgcnn_gn_second_dataset_confirmation"
     / "BNCI2015_001_dgcnn_gn_2nd_dataset_summary.json", "BNCI2015_001 (binary, chance 0.50); all folds confirmation"),
]

PER_FOLD_COLS = ["fold", "heldout_subject", "erm_src_bacc", "reg_src_bacc", "src_drop",
                 "erm_graph_kl", "reg_graph_kl", "graph_reduction", "node_reduction",
                 "reg_clears_g", "reg_clears_n", "source_retained", "target_guardrail", "fold_pass"]

# Static claims-scope (from CIGL_32; needs no JSON). Phrases are asserted by the tests.
CLAIMS_SCOPE = {
    "estimator": "posterior-KL proxy (NOT unbiased CMI)",
    "setting": "strict source-only DG (target labels evaluation-only)",
    "effect": "partial, reproducible graph/node leakage reduction at task retention (NOT elimination)",
    "datasets": "two MI datasets (BNCI2014_001, BNCI2015_001)",
    "backbone": "DGCNN static-adjacency adapter (one backbone)",
    "config": "fixed graph_node_010 (lambda_g=lambda_node=0.010, lambda_edge=0); no lambda-grid",
    "edge": "no edge-CMI (static adjacency; edge object absent)",
    "sota": "no SOTA / no leaderboard claim",
    "generality": "no cross-architecture and no beyond-MI claim",
}


def _fold_rows(summary):
    rows = []
    for f in sorted(summary.get("per_fold", {}), key=lambda x: int(x)):
        pf = summary["per_fold"][f]
        e, r, fl = pf.get("erm_fixed", {}), pf.get("graph_node_010", {}), pf.get("flags", {})
        rows.append({
            "fold": f, "heldout_subject": pf.get("heldout_subject"),
            "erm_src_bacc": round(e.get("source_probe_bacc") or 0.0, 3),
            "reg_src_bacc": round(r.get("source_probe_bacc") or 0.0, 3),
            "src_drop": round(fl.get("source_drop_vs_erm") or 0.0, 3),
            "erm_graph_kl": round(e.get("graph_kl_mean") or 0.0, 3),
            "reg_graph_kl": round(r.get("graph_kl_mean") or 0.0, 3),
            "graph_reduction": (None if fl.get("graph_reduction") is None else round(fl["graph_reduction"], 3)),
            "node_reduction": (None if fl.get("node_reduction") is None else round(fl["node_reduction"], 3)),
            "reg_clears_g": r.get("graph_clears_seeds"), "reg_clears_n": r.get("node_clears_seeds"),
            "source_retained": fl.get("source_retained"), "target_guardrail": fl.get("target_guardrail"),
            "fold_pass": fl.get("fold_pass")})
    return rows


def _verdict(summary):
    for k in ("second_dataset_confirmation", "folds1_8_confirmation"):
        if k in summary:
            return summary[k]
    return {}


def _write_csv(path, cols, rows):
    with open(path, "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=cols)
        w.writeheader()
        for r in rows:
            w.writerow({c: r.get(c) for c in cols})


def _write_md_table(path, title, cols, rows, footer=""):
    lines = [f"# {title}", "", "| " + " | ".join(cols) + " |", "|" + "|".join(["---"] * len(cols)) + "|"]
    for r in rows:
        lines.append("| " + " | ".join(str(r.get(c)) for c in cols) + " |")
    if footer:
        lines += ["", footer]
    path.write_text("\n".join(lines) + "\n")


def _write_claims_scope(path):
    lines = ["# CIGL claims scope (Phase 4A)", "",
             "Bounded claims for the CIGL graph/node method (see docs/CIGL_32). Generated by",
             "scripts/collect_cigl_evidence_tables.py — no training, no GPU.", "",
             "| aspect | scope |", "|---|---|"]
    for k, v in CLAIMS_SCOPE.items():
        lines.append(f"| {k} | {v} |")
    lines += ["", "Allowed: significant graph/node label-conditional domain leakage on a task-capable graph",
              "backbone; a fixed graph/node CMI regularizer partially+reproducibly reduces it at task retention",
              "on two MI datasets, source-only. Forbidden: SOTA, edge-CMI, leakage *elimination*, unbiased CMI,",
              "cross-architecture or beyond-MI generality, lambda-robustness."]
    path.write_text("\n".join(lines) + "\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out_dir", default=str(RESULTS / "paper_tables"))
    ap.add_argument("--dry_run", action="store_true",
                    help="tolerate missing summary JSON (warn instead of error)")
    args = ap.parse_args()
    out = Path(args.out_dir)
    out.mkdir(parents=True, exist_ok=True)

    written, warnings = [], []
    for label, jpath, note in CONFIRMATIONS:
        if not jpath.exists():
            msg = f"[collect] MISSING summary JSON for {label}: {jpath} (gitignored/regenerable; run the phase or use the tracked CIGL doc)"
            warnings.append(msg); print(msg)
            continue
        summary = json.loads(jpath.read_text())
        rows = _fold_rows(summary)
        v = _verdict(summary)
        foot = (f"Verdict: source_only_confirmed={v.get('source_only_confirmed')}, "
                f"target_guardrail_pass={v.get('target_guardrail_pass')}, "
                f"confirmed_with_target_guardrail={v.get('confirmed_with_target_guardrail', v.get('confirmed'))}, "
                f"decision={v.get('decision')}. {note}")
        _write_csv(out / f"table_{label}.csv", PER_FOLD_COLS, rows)
        _write_md_table(out / f"table_{label}.md", f"CIGL {label} (per-fold)", PER_FOLD_COLS, rows, foot)
        written += [str(out / f"table_{label}.csv"), str(out / f"table_{label}.md")]
        print(f"[collect] wrote {label}: {len(rows)} folds -> {out / ('table_'+label+'.md')}")

    _write_claims_scope(out / "table_claims_scope.md")
    written.append(str(out / "table_claims_scope.md"))
    print(f"[collect] wrote claims scope -> {out / 'table_claims_scope.md'}")

    if warnings and not args.dry_run:
        print(f"[collect] {len(warnings)} summary JSON(s) missing; claims-scope still written. "
              f"(Use --dry_run to suppress this as an error-style note.)")
    print(f"[collect] done. {len(written)} files under {out}. No training / no GPU.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
