"""Table 3 -- frozen-erasure TARGET-DEPLOYMENT test (Step 3). Built from erasure_target_deploy_summary.json so
numbers stay locked to tos_cmi/eeg/erasure_target_deploy.py. Emits figures/table3_erasure_target.tex (booktabs)
+ prints markdown. Message: deployed on the held-out target (source-only fit), NO eraser improves target
balanced accuracy; the only NLL movement is non-specific (random-k gives a same-sign drop); INLP "improves"
NLL only by collapsing the task.
  python -m tos_cmi.paper.scripts.build_table3_erasure_target
"""
import json
import os
from . import plot_style as ps

EEG = os.path.join(ps.ROOT, "tos_cmi", "results", "tos_cmi_eeg_frozen")
METHODS = ["full", "TOS_VD", "LEACE", "RLACE", "INLP", "random_k"]
MLABEL = {"full": "(none)", "TOS_VD": "TOS ($V_D$)", "LEACE": "LEACE", "RLACE": "RLACE",
          "INLP": "INLP", "random_k": "random-$k$"}
NOTE = {"full": "reference (no erasure)",
        "TOS_VD": "low-rank deletion; no target change",
        "LEACE": "optimal linear eraser; no bAcc gain",
        "RLACE": "rank-$k$ adversarial; no bAcc gain",
        "INLP": "collapses the task (bAcc $\\to$ chance)",
        "random_k": "same-$k$ random; same-sign NLL drop $\\Rightarrow$ non-specific"}


def _ci(m, lo, hi):
    return "$%+.3f$ {\\scriptsize[$%+.3f,%+.3f$]}" % (m, lo, hi)


def main():
    j = json.load(open(os.path.join(EEG, "erasure_target_deploy", "erasure_target_deploy_summary.json")))
    S = j["summary"]
    cols = ["Backbone", "Method", "tgt bAcc", "tgt NLL", "$\\Delta$bAcc [95\\% CI]",
            "$\\Delta$NLL [95\\% CI]", "src bAcc", "subj dec"]
    rows = []
    for bb in ["TSMNet", "EEGNet"]:
        ch = S["%s|full" % bb]["chance_task"]
        tag = "%s" % bb
        for i, m in enumerate(METHODS):
            r = S["%s|%s" % (bb, m)]
            db = "(ref)" if m == "full" else _ci(r["dtgt_bacc"], r["dtgt_bacc_lo"], r["dtgt_bacc_hi"])
            dn = "(ref)" if m == "full" else _ci(r["dtgt_nll"], r["dtgt_nll_lo"], r["dtgt_nll_hi"])
            rows.append([tag if i == 0 else "", MLABEL[m], "%.3f" % r["tgt_bacc_mean"],
                         "%.3f" % r["tgt_nll_mean"], db, dn, "%.3f" % r["src_bacc_mean"],
                         "%.3f" % r["subj_dec_after_mean"], NOTE[m]])
    lines = ["% Auto-generated by tos_cmi/paper/scripts/build_table3_erasure_target.py. Do not hand-edit values.",
             "% Requires: \\usepackage{booktabs,tabularx}",
             "\\begin{table*}[t]\\centering\\footnotesize",
             "\\caption{\\textbf{Frozen-erasure target-deployment test (BCI-IV-2a, LOSO; source-only fit, "
             "mean over 3 seeds $\\times$ 9 folds; paired fold-cluster 95\\% CI vs.\\ full $Z$; target chance "
             "bAcc $0.25$).} Each eraser is fit on source, applied to source and the held-out target, a linear "
             "task head is trained on transformed source, and evaluated on the transformed target; the target "
             "is never used for fitting, selection, or calibration. \\emph{No eraser improves target balanced "
             "accuracy} on either backbone (all $\\Delta$bAcc CIs overlap or fall below zero; INLP collapses "
             "the task to chance). The only positive movement is a small NLL reduction, but it is not erasure-specific: same-$k$ "
             "\\emph{random} removal produces a same-sign reduction without erasing subject identity, and INLP's "
             "NLL drop coincides with task collapse --- not a domain-removal benefit.}",
             "\\label{tab:target_deploy}",
             "\\begin{tabularx}{\\linewidth}{l l c c c c c c}",
             "\\toprule",
             " & ".join(cols) + " \\\\", "\\midrule"]
    for i, r in enumerate(rows):
        if i == len(METHODS):
            lines.append("\\midrule")
        lines.append(" & ".join(str(c) for c in r[:8]) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabularx}", "\\end{table*}"]
    out = os.path.join(ps.FIGDIR, "table3_erasure_target.tex")
    os.makedirs(ps.FIGDIR, exist_ok=True); open(out, "w").write("\n".join(lines) + "\n")
    print("wrote", out)
    hdr = cols + ["note"]
    print("\n| " + " | ".join(c.replace("\\", "").replace("$", "") for c in hdr) + " |")
    for r in rows:
        print("| " + " | ".join(str(c).replace("\\", "").replace("$", "") for c in r) + " |")
    print("TABLE3_DONE")


if __name__ == "__main__":
    main()
