"""Table 1 -- one-glance summary across representations (TSMNet vs EEGNet), built from saved artifacts so
its numbers are locked to Fig 3/4/5. CSV is the canonical machine-readable artifact; LaTeX (booktabs) is a
generated VIEW (do not hand-edit). Target DG metric = MEAN LOSO target bAcc with a paired-t vs lambda=0
(standard DG aggregation; the median obscures the paired decline -- see口径 note).
Run: python -m tos_cmi.paper.scripts.build_table1_summary [--csv] [--latex]   (default: both)
"""
import argparse
import csv
import glob
import json
import os
from ._data import load_ablation, load_lpc_sweep, LPC
from . import plot_style as ps


def _paired_t(backbone, lam_a, lam_b, field="final_target_bAcc"):
    """paired (by subject,seed) t-test of field at lam_b vs lam_a over the raw LPC sweep."""
    d = os.path.join(LPC, backbone)
    def keyed(lam):
        out = {}
        for p in glob.glob(os.path.join(d, "*sub*_lam%g_seed*.json" % lam)):
            b = os.path.basename(p)
            if "scale_invariant" in b or "warm_ramp" in b:
                continue
            r = json.load(open(p)); out[(r.get("target_subject"), r.get("seed"))] = r.get(field)
        return out
    ka, kb = keyed(lam_a), keyed(lam_b)
    pairs = [(ka[k], kb[k]) for k in ka if k in kb and ka[k] is not None and kb[k] is not None]
    if len(pairs) < 3:
        return None
    try:
        from scipy import stats
        import numpy as np
        a = np.array(pairs); t, p = stats.ttest_rel(a[:, 1], a[:, 0])
        return {"delta": float((a[:, 1] - a[:, 0]).mean()), "p": float(p), "n": len(pairs)}
    except Exception:
        return None


def _row(bb):
    a = load_ablation(bb); s = load_lpc_sweep(bb); m = a["metrics"]; pl = s["per_lam"]
    dZ = m["domain_Z_mlp"]["mean"]; dRZ = m["domain_RZ_mlp"]["mean"]; dRr = m["domain_Rrand_mlp"]["mean"]
    dZl = m["domain_Z_linear"]["mean"]; dRZl = m["domain_RZ_linear"]["mean"]
    tZ = m["task_Z_mlp"]["mean"]; tRZ = m["task_RZ_mlp"]["mean"]
    lo = min(pl); hi = 3.0 if 3.0 in pl else max(pl)
    subj0 = pl[lo]["subj"]["mean"]; subjhi = pl[hi]["subj"]["mean"]            # MEAN口径
    tgt0 = pl[lo]["tgt"]["mean"]; tgthi = pl[hi]["tgt"]["mean"]               # MEAN口径
    pt = _paired_t(bb, lo, 1.0) or _paired_t(bb, lo, hi)
    pstr = (", paired-t p%s" % ("<0.001" if pt["p"] < 1e-3 else "=%.3f" % pt["p"])) if pt else ""
    if bb == "TSMNet":
        raw_lpc = "leakage falls via collapse (feature-norm to 0), task to chance"
        cf_lpc = "task restored, leakage returns to ERM (subj ~0.997)"
        delete_eff = "dents only: subj %.2f to %.2f (= random %.2f); task kept" % (dZ, dRZ, dRr)
        dg = "not achievable (no task-preserving leakage reduction: raw LPC collapses; collapse-free LPC removes none)"
        decision = "abstain / low-rank deletion insufficient"
    else:
        raw_lpc = "no collapse: leakage falls %.2f to %.2f, source task degrades gradually" % (subj0, subjhi)
        cf_lpc = "raw LPC already collapse-free on this latent"
        delete_eff = "removes: subj linear %.2f to %.2f / MLP %.2f to %.2f (>> random %.2f); task kept" % (dZl, dRZl, dZ, dRZ, dRr)
        dg = "none: mean target %.2f to %.2f%s as leakage falls %.2f to %.2f" % (tgt0, tgthi, pstr, subj0, subjhi)
        decision = "diagnostic deletion removes leakage but no DG gain"
    return {
        "Backbone": bb, "Latent dim": str(a["z_dim"]),
        "Subject decode (ERM)": "%.3f" % dZ,
        "Low-rank deletion (subject; task)": delete_eff,
        "Raw LPC outcome": raw_lpc,
        "Collapse-free LPC outcome": cf_lpc,
        "DG gain under task-preserving control": dg,
        "Certified / diagnostic decision": decision,
    }


NOTE = ("Target DG = MEAN LOSO target balanced accuracy over folds x seeds (paired-t vs lambda=0). "
        "Deletion decisions are diagnostic unless the exact certificate scope is reached.")


def _latex(rows, cols, path):
    # transposed: properties as rows, backbones as columns (long cells wrap in X columns).
    esc = lambda s: str(s).replace("_", "\\_").replace("%", "\\%").replace(">>", "$\\gg$").replace(" to ", " $\\to$ ")
    bbs = [r["Backbone"] for r in rows]
    lines = [
        "% Auto-generated by tos_cmi/paper/scripts/build_table1_summary.py.",
        "% Do not edit values manually; edit the source builder or artifact loaders.",
        "% Requires: \\usepackage{booktabs,tabularx,makecell}",
        "\\begin{table}[t]\\centering\\footnotesize",
        "\\caption{Measurement-to-control summary across EEG representations (BCI-IV-2a, LOSO). "
        + esc(NOTE) + "}",
        "\\label{tab:summary}",
        "\\begin{tabularx}{\\linewidth}{l " + " ".join(["X"] * len(bbs)) + "}",
        "\\toprule",
        "Property & " + " & ".join("\\textbf{%s}" % esc(b) for b in bbs) + " \\\\",
        "\\midrule",
    ]
    for c in cols:
        if c == "Backbone":
            continue
        cells = " & ".join("\\makecell[tl]{%s}" % esc(r[c]) for r in rows)
        lines.append("%s & %s \\\\" % (esc(c), cells))
    lines += ["\\bottomrule", "\\end{tabularx}", "\\end{table}"]
    open(path, "w").write("\n".join(lines) + "\n")
    print("wrote", path)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", action="store_true"); ap.add_argument("--latex", action="store_true")
    args = ap.parse_args()
    do_csv = args.csv or not (args.csv or args.latex)
    do_tex = args.latex or not (args.csv or args.latex)
    rows = [_row("TSMNet"), _row("EEGNet")]
    cols = list(rows[0].keys())
    os.makedirs(ps.FIGDIR, exist_ok=True)
    if do_csv:
        out = os.path.join(ps.FIGDIR, "table1_summary.csv")
        with open(out, "w", newline="") as f:
            w = csv.DictWriter(f, fieldnames=cols + ["_note"]); w.writeheader()
            for r in rows:
                w.writerow({**r, "_note": NOTE})
        print("wrote", out)
    if do_tex:
        _latex(rows, cols, os.path.join(ps.FIGDIR, "table1_summary.tex"))
    print("\n| " + " | ".join(cols) + " |")
    for r in rows:
        print("| " + " | ".join(r[c] for c in cols) + " |")
    print("note:", NOTE)
    print("TABLE1_DONE")


if __name__ == "__main__":
    main()
