"""Table 2 -- linear concept-erasure controls vs TOS deletion (Track G). Built from the erasure_report.json
of each backbone so numbers stay locked to tos_cmi/eeg/erasure_baselines.py. Emits figures/table2_erasure.tex
(booktabs) + prints markdown. Message: the projector is not the contribution (LEACE >= TOS at equal task
cost); the gap is not a weak-eraser artifact.
  python -m tos_cmi.paper.scripts.build_table2_erasure
"""
import json
import os
from . import plot_style as ps

EEG = os.path.join(ps.ROOT, "tos_cmi", "results", "tos_cmi_eeg_frozen")
METHODS = ["full", "LEACE", "RLACE", "INLP", "TOS_VD", "random_k"]
MLABEL = {"full": "(none)", "LEACE": "LEACE", "RLACE": "RLACE", "INLP": "INLP",
          "TOS_VD": "TOS ($V_D$)", "random_k": "random-$k$"}
INTERP = {"full": "reference (no erasure)",
          "LEACE": "optimal linear eraser; strongest linear removal at near-zero task cost",
          "RLACE": "rank-$k$ adversarial; rank-limited erasure",
          "INLP": "erases but destroys the task (over-erasure)",
          "TOS_VD": "low-rank score-Fisher deletion (rank-limited)",
          "random_k": "same-$k$ random removal (control)"}


def _bb(name):
    a = json.load(open(os.path.join(EEG, "BNCI2014_001_%s_LOSO" % name, "erasure_report.json")))["aggregate"]
    return a


def main():
    aggs = {n: _bb(n) for n in ["TSMNet", "EEGNet"]}
    cols = ["Backbone", "Method", "Subj.\\ lin.", "Subj.\\ MLP", "Task lin.", "Interpretation"]
    rows = []
    for bb in ["TSMNet", "EEGNet"]:
        a = aggs[bb]; tag = "%s ($d_z{=}%d$)" % (bb, a["z_dim"])
        for i, m in enumerate(METHODS):
            rows.append([tag if i == 0 else "", MLABEL[m],
                         "%.2f" % a["subj_%s_lin" % m], "%.2f" % a["subj_%s_mlp" % m],
                         "%.2f" % a["task_%s_lin" % m], INTERP[m]])
    # LaTeX (booktabs + tabularx; Interpretation column wraps)
    esc = lambda s: str(s)
    lines = ["% Auto-generated by tos_cmi/paper/scripts/build_table2_erasure.py. Do not hand-edit values.",
             "% Requires: \\usepackage{booktabs,tabularx}",
             "\\begin{table}[t]\\centering\\footnotesize",
             "\\caption{Linear concept-erasure controls show the projector is not the contribution "
             "(BCI-IV-2a, frozen latents; subject decode after erasing $D$, lower is more removed; chance "
             "subj.\\ $0.125$, task $0.250$; task linear before erasure $0.75$/$0.64$). LEACE (optimal "
             "closed-form linear erasure) removes more subject information than the TOS deletion at equal "
             "task cost, yet a large nonlinearly-recoverable MLP residual remains (TSMNet $0.74$ vs EEGNet "
             "$0.39$); INLP erases only by destroying the task; rank-limited erasers (RLACE, TOS) fail on "
             "the redundant high-dimensional TSMNet latent.}",
             "\\label{tab:erasure}",
             "\\begin{tabularx}{\\linewidth}{l l c c c X}",
             "\\toprule",
             " & ".join(cols) + " \\\\", "\\midrule"]
    for i, r in enumerate(rows):
        if i == len(METHODS):
            lines.append("\\midrule")
        lines.append(" & ".join(esc(c) for c in r) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabularx}", "\\end{table}"]
    out = os.path.join(ps.FIGDIR, "table2_erasure.tex")
    os.makedirs(ps.FIGDIR, exist_ok=True); open(out, "w").write("\n".join(lines) + "\n")
    print("wrote", out)
    print("\n| " + " | ".join(c.replace("\\", "") for c in cols) + " |")
    for r in rows:
        print("| " + " | ".join(str(c) for c in r) + " |")
    print("TABLE2_DONE")


if __name__ == "__main__":
    main()
