"""Big-N multi-dataset validation tables (Case 1). Reads the committed analyzer outputs (deployment summaries
+ erasure_report + validation_manifest) via bigN_report's verdict logic, and emits:
  figures/table_bigN_compact.tex   -- compact MAIN-text table (dataset group x valid cells x C12 verdict)
  figures/table_bigN_full.tex      -- full APPENDIX table (per cell: C7/C8, C12, LEACE/TOS/RLACE dbAcc[CI],
                                      INLP source-task drop, random-k)
Numbers stay locked to tos_cmi/eeg/{erasure_target_deploy, erasure_baselines}.py. No recompute.
  python -m tos_cmi.paper.scripts.build_table4_bigN
"""
import os
from . import plot_style as ps
from tos_cmi.eeg import bigN_report as B

# (moabb name, display, subjects, classes)
DATASETS = [("BNCI2014_001", "BCI-IV-2a", 9, 4), ("BNCI2014_004", "BCI-IV-2b", 9, 2),
            ("Lee2019_MI", "Lee2019", 54, 2), ("Cho2017", "Cho2017", 52, 2),
            ("Schirrmeister2017", "High-Gamma", 14, 4)]
PRIN = ["LEACE", "TOS_VD", "RLACE"]
MLBL = {"LEACE": "LEACE", "TOS_VD": "TOS", "RLACE": "RLACE"}


def _cells(ds):
    """-> list of (backbone, c78, c12, rows, full) for the valid backbones of a dataset."""
    S = B._deploy_summary(ds)
    out = []
    for bb in ("EEGNet", "TSMNet"):
        agg = B._erasure_report(ds, bb)
        has = S and any(k.startswith(bb + "|") for k in S.get("summary", {}))
        if not agg and not has:
            out.append((bb, "DEGENERATE", "DEGENERATE", {}, {}))
            continue
        c78 = B._c78_verdict(agg) if agg else "N/A"
        c12, rows = B._c12_verdict(S, bb) if S else ("N/A", {})
        full = S["summary"].get("%s|full" % bb, {}) if S else {}
        out.append((bb, c78, c12.split()[0], rows, full))
    return out


def _ci(r):
    return "$%+.3f$\\,[$%+.3f,%+.3f$]" % (r["dtgt_bacc"], r["dtgt_bacc_lo"], r["dtgt_bacc_hi"])


def build_compact():
    lines = ["% Auto-generated by build_table4_bigN.py. Do not hand-edit.",
             "\\begin{table}[t]\\centering\\footnotesize",
             "\\caption{\\textbf{Multi-dataset target-deployment validation of C12.} Valid (dataset, backbone) "
             "cells and the C12 verdict (no principled source-fitted eraser --- LEACE/TOS/RLACE --- yields a "
             "practically meaningful target-bAcc gain: all upper $95\\%$ CIs $<{+}0.01$). 2b-TSMNet is excluded "
             "as a degenerate $3$-channel SPD configuration, not a negative cell. Full per-eraser table with "
             "CIs in App.~\\ref{tab:bigN_full}.}",
             "\\label{tab:bigN_compact}",
             "\\begin{tabularx}{\\linewidth}{l c c X}", "\\toprule",
             "Dataset & Subj. & Valid cells & C12 verdict / note \\\\", "\\midrule"]
    notes = {"BCI-IV-2a": "original mechanism dataset", "BCI-IV-2b": "TSMNet degenerate (3\\,ch)",
             "Lee2019": "EEGNet erasure not task-safe", "Cho2017": "non-degenerate TSMNet, big-$N$",
             "High-Gamma": "4-class, 128\\,ch"}
    for ds, disp, subj, ncls in DATASETS:
        cells = _cells(ds)
        valid = [c for c in cells if c[2] not in ("DEGENERATE", "N/A")]
        nvalid = len(valid)
        allc = all(c[2] == "CONFIRM" for c in valid) and nvalid > 0
        verdict = "CONFIRM" if allc else "/".join(sorted(set(c[2] for c in valid)))
        lines.append("%s & %d & %d/2 & \\textbf{%s} --- %s \\\\" % (disp, subj, nvalid, verdict, notes[disp]))
    lines += ["\\bottomrule", "\\end{tabularx}", "\\end{table}"]
    return "\n".join(lines) + "\n"


def build_full():
    cols = "l l c c c c c c"
    lines = ["% Auto-generated by build_table4_bigN.py. Do not hand-edit.",
             "\\begin{table*}[t]\\centering\\scriptsize\\setlength{\\tabcolsep}{3.5pt}",
             "\\caption{\\textbf{Full multi-dataset target-deployment table.} Per (dataset, backbone): C7/C8 "
             "source-side erasure profile, C12 verdict, and each eraser's target $\\Delta$bAcc vs full $Z$ "
             "(paired subject-cluster $95\\%$ CI; LOSO fold = one held-out target subject; 3 seeds). INLP always "
             "collapses the source task (drop shown); random-$k$ is a non-specific control. 2b-TSMNet is "
             "degenerate (3-channel SPD $\\to$ ill-conditioned tangent metric).}",
             "\\label{tab:bigN_full}",
             "\\resizebox{\\linewidth}{!}{%",
             "\\begin{tabular}{%s}" % cols, "\\toprule",
             "Dataset & BB & C7/8 & C12 & LEACE $\\Delta$bAcc & TOS $\\Delta$bAcc & RLACE $\\Delta$bAcc & "
             "INLP (src task) \\\\", "\\midrule"]
    for ds, disp, subj, ncls in DATASETS:
        for i, (bb, c78, c12, rows, full) in enumerate(_cells(ds)):
            tag = disp if i == 0 else ""
            if c12 == "DEGENERATE":
                lines.append("%s & %s & --- & \\emph{degenerate} & \\multicolumn{4}{c}{3-channel SPD "
                             "metric ill-conditioned; all folds skipped} \\\\" % (tag, bb))
                continue
            le = _ci(rows["LEACE"]) if "LEACE" in rows else "---"
            to = _ci(rows["TOS_VD"]) if "TOS_VD" in rows else "---"
            rl = _ci(rows["RLACE"]) if "RLACE" in rows else "---"
            inlp = "N/A"
            S = B._deploy_summary(ds)
            ir = S["summary"].get("%s|INLP" % bb) if S else None
            if ir and full:
                inlp = "$%+.3f$\\,{\\tiny($%.2f{\\to}%.2f$)}" % (
                    ir["dtgt_bacc"], full.get("src_bacc_mean", float('nan')), ir.get("src_bacc_mean", float('nan')))
            lines.append("%s & %s & %s & \\textbf{%s} & %s & %s & %s & %s \\\\"
                         % (tag, bb, c78, c12, le, to, rl, inlp))
        lines.append("\\midrule")
    lines[-1] = "\\bottomrule"
    lines += ["\\end{tabular}}", "\\end{table*}"]
    return "\n".join(lines) + "\n"


def main():
    os.makedirs(ps.FIGDIR, exist_ok=True)
    for name, txt in [("table_bigN_compact.tex", build_compact()), ("table_bigN_full.tex", build_full())]:
        open(os.path.join(ps.FIGDIR, name), "w").write(txt)
        print("wrote", name)
    print("TABLE4_BIGN_DONE")


if __name__ == "__main__":
    main()
